#pragma once
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <string>
#include <iostream>
#include "Public/IndexBuffer.h"
#include "Public/VertexBuffer.h"
#include "Public/VertexArray.h"
#include "Public/Shader.h"
#include "Public/Renderer/Renderer.h"
#include "Public/Input.h"
#include "Public/Texture.h"
#include "Public/Time.h"
#include "Public/CustomTemplate.h"
#include "Public/Renderer/MeshFilter.h"
#include "Public/Renderer/MeshRenderer.h"
#include "Public/Renderer/Screen.h"
#include "Public/Maths.h"
#include <Windows.h>
#include "Public/Physics/Physics2D/Physics2D.h"
#include "Public/Physics/Physics2D/RigidBody2D.h"
#include "Public/Renderer/RenderPipeline.h"
#include "Public/Renderer/Camera/Camera.h"
#include "Public/Renderer/Camera/OrthographicCamera.h"
 #include <Core/Vendor/glm/glm.hpp>
#include <Core/Vendor/glm/gtc/matrix_transform.hpp>
#include <Core/Public/UI/DetectCollisionUI.h>